---
title: "WCS Strongholds"
author: "Vanessa Rathbone"
date: "10/6/2021"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

library(raster)
library(tidyverse)
library(sf)
library(here)
library(janitor)
library(fasterize)
library(lwgeom)


```

```{r}

#Read in, tidy up the data and convert to rasters
continents <- read_sf(here("continents", "4a7d27e1-84a3-4d6a-b4c2-6b6919f3cf4b202034-1-2zg7ul.ht5ut.shp")) %>% 
  clean_names()

st_crs(continents)

plot(continents)

#strongholds
strongholds <- read_sf(here("strongholds", "STHOLDS_intersect.shp")) %>%
  clean_names()

# strongholds$geometry %>% 
#   s2::s2_rebuild()

st_crs(strongholds)

# sf::sf_use_s2(FALSE)

strong_rast <- raster(extent(strongholds)) #convert to raster
values(strong_rast) <- 1:ncell(strong_rast) #add cell values
strong_rast <-mask(strong_rast, continents) #mask to continents

plot(strong_rast)


#where we work
www <- read_sf(here("www", "www_intersect.shp")) %>% 
  clean_names() %>% 
  st_transform(., crs = st_crs(continents)) #change to correct crs

st_crs(www)

www_rast <- raster(extent(www))
values(www_rast) <- 1:ncell(www_rast)
www_rast <-mask(www_rast, continents)

plot(www_rast)

www_df <- www_rast %>% #create df
  as.data.frame()


```


Area
```{r}

#total area

#Strongholds
strong_area <- strongholds %>% 
  mutate(area = st_area(geometry)/1e+6) %>%  #convert sq meters to sq km

strong_tot_area <- strong_area %>%
  select() %>% 
  mutate()

#WWW
www_area <- www %>% 
  mutate(area = st_area(geometry)/1e+6) 



###########

#terrestrial area and % of total terrestrial area, Earth's surface: 510,000,000 km2

strong_area_terr <- strong_area %>% 
  group_by(continent) %>% 
  summarise(sum_area_k2 = sum(sqkm)) %>% 
  mutate(sum_total = sum(sum_area_k2)) %>% 
  mutate(sum_perc = sum_total/510000000)

www_area_cont <- www_area %>% 
  group_by(continent) %>% 
  summarise(sum_area_k2 = sum(sqkm)) %>% 
  mutate(sum_total = sum(sum_area_k2)) %>% 
  mutate(sum_perc = sum_total/510000000)

##########

#marine area

#%of total marine area



```

Biodiversity
```{r}

#number of Threatened Species

#IUCN Red List Species Category by animal category by # and by % of global total

#Marine species represented

############

#Cats and dogs

# total number of species
# total number of threatened species
# total number of threatened species distribution
# total number of threatened species population

```

